### ISSUE TITLE
What is /usr/lib/.build-id

### ISSUE THREAD

**Issue by FabriceSalvaire** [FabriceSalvaire/copr-mao#2]
/usr/lib/.build-id
/usr/lib/.build-id/e6
/usr/lib/.build-id/e6/a55a56c2b045d89cd67f65d7ffb4a1c87cc89c

**Comment by igor-raits** [comment]
Just do not touch it

**Comment by FabriceSalvaire** [comment]
but what it is ???

**Comment by igor-raits** [comment]
This is debuginfo symlinks which are needed for proper debuginfo RPM packages integration.

**Comment by FabriceSalvaire** [comment]
ok I was not aware

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/developer_guide/compiling-build-id
